(TeX-add-style-hook "ecrc-template"
 (lambda ()
    (LaTeX-add-bibliographies
     "reference")
    (LaTeX-add-labels
     "section1"
     "fig:global"
     "fig:local"
     "fig:the correspondence decision"
     "section2"
     "fig:bridge-nc"
     "fig:bridge-c"
     "fig:bridges"
     "fig:branch-contour"
     "fig:branch-hull"
     "fig:branch-bridge"
     "fig:branch-but"
     "fig:branch-middle"
     "fig:branches"
     "section3"
     "fig:fluent"
     "ffd"
     "formula:theta"
     "formula:original"
     "formula:deformation"
     "formula:data-driven"
     "formula:smoothness"
     "formula:energy"
     "fig:FFD_original_2_3"
     "fig:FFD_lattice_2_3"
     "fig:FFD_transformed_2_3"
     "fig:FFD_correspond_2_3"
     "fig:FFD_surface_2_3"
     "fig:FFD_Result"
     "medial axis"
     "fig:circle_ellipse_original_points"
     "fig:circle_ellipse_transformed"
     "fig:circle_ellipse_correspondence"
     "fig:circle_ellipse_surface"
     "fig:branches without medial axis"
     "fig:circle_ellipse_meidal_original_points"
     "fig:circle_ellipse_medial_transformed"
     "fig:circle_ellipse_medial_correspondence"
     "fig:circle_ellipse_medial_surface"
     "fig:branches with medial axes"
     "fig:Medial_original_20_21"
     "fig:Medial_transformed_20_21"
     "fig:Medial_correspond_20_21"
     "fig:Medial_surface_20_21"
     "section4")
    (TeX-run-style-hooks
     "rotating"
     "figuresright"
     "amssymb"
     "amsmath"
     "subcaption"
     "graphicx"
     "ecrc"
     ""
     "latex2e"
     "elsarticle10"
     "elsarticle"
     "times"
     "3p")))

